#!/bin/bash

DOTFILES_ROOT=$(pwd)

#symlink dotfiles into home directory
install_dotfiles () {

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find "$DOTFILES_ROOT/" -maxdepth 2 -name '*.symlink')
  do
    dst="$HOME/$(basename "${src%.*}")"
    echo $dst 
    ln -s "$src" "$dst"
  done
}

install_dotfiles

echo "dotfiles installed."

#setup oh-my-zsh
#git clone https://github.com/robbyrussell/oh-my-zsh ~/.oh-my-zsh
cd ~/.oh-my-zsh/custom/plugins
git clone git://github.com/zsh-users/zsh-syntax-highlighting.git
#setup pure theme for zsh
cd ~/.oh-my-zsh/custom/
git clone https://github.com/sindresorhus/pure
mv pure/pure.zsh pure.zsh-theme
mv pure/async.zsh async.zsh
rm ~/.oh-my-zsh/themes/pure.zsh-theme
# set terminal theme
cd $DOTFILES_ROOT
bash terminal-theme.sh


#setup spacemacs
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
